### ISSUE TITLE
Box2D is dead?

### ISSUE THREAD

**Issue by hcorion** [erincatto/Box2D#395]
From the latest commit (as of 1/26/2016): 
The main Box2D library is open source, but not open contribution. Please do not submit pull requests. Exceptions may be considered for build files and other items that are not part of the main library source. Thank you for your understanding.

Does this mean Box2D is dead?

**Comment by erincatto** [comment]
No. I haven't had time lately to work on Box2D, but I plan to return to it in the future. Even then, it will not be open contribution.

**Comment by Alicemargatroid** [comment]
@erincatto Why in the world would you not accept pull requests? This really turns me off to this physics engine; if I find a bug and can't contribute back, what was the point of making it open source?

**Comment by erincatto** [comment]
I do not accept pull requests because Box2D is not open contribution. If you find a bug, please file an issue. Filing issues is a meaningful contribution.

**Comment by JesseTG** [comment]
He's asking why it's not open contribution.

**Comment by erincatto** [comment]
Think of Box2D as a book. You can tell someone about errors in their book. But you do not get to add your own chapters to their book.

**Comment by JesseTG** [comment]
I disagree with that analogy.  A book, once published, is a more or less static entity.  Active open source software projects are anything but, and to treat one as such is an entirely artificial constraint.

No, @Alicemargatroid (and I, and probably others too) are curious about why you're turning down the opportunity for contributors to do work *for you for free*, especially since you've expressed a recent dearth of spare time to dedicate to this project.  Sure, we can fork this, but then we'd have to get the word out about our own fork in order for anyone to take advantage of bug fixes, new features, etc., thus robbing users (and developers of ports, wrappers, and bindings) the convenience of `git pull origin master`.

To be honest, I think you're being difficult and prideful.  There are literally [*billions*](https://en.wikipedia.org/wiki/Angry_Birds) of devices out there with a game that uses Box2D.  Deservedly so; Box2D is great, and that's exactly why we want to help improve it.  If you let that happen, the engine will be all the better for it.

**Comment by Alicemargatroid** [comment]
@erincatto Except books aren't open source and licensed under the zlib license. That analogy makes no sense; why have an open source github repo if you aren't accepting pull requests?

**Comment by erincatto** [comment]
Good point. I would prefer to have a host that provides source control, issue filing, and a wiki.

**Comment by JesseTG** [comment]
Who says that you'd lose ownership of your work?  From a legal standpoint the license has you covered.  From a moral standpoint, you're the gatekeeper for all proposed changes.

And the other stuff can be done if contributions are accepted, too.

**Comment by Alicemargatroid** [comment]
@erincatto Other git (or mercurial) repository websites exist, that allow more control, such as gitgud.io

However, the license itself is the problem; zlib allows forking, relicensing under GPL or BSD, and a whole host of other things. Licensing under such an open and expressive license _affords_ contributing back, much like a flat door handle _affords_ pushing it; it's implicit to how they work.

With open source inherently comes open contribution (even if that contribution is limited or managed by the author, as is github's model); that doesn't mean you lose ownership or control or anything.

**Comment by erincatto** [comment]
I think it would be ethically (and probably legally) wrong for me to sell a version of Box2D in the future if that version contained major pieces of code written by other people. I'm not saying that is my plan, but I don't want to rule it out.

I'm totally fine with forking. I'm fine with giving other people control of their version of Box2D. I just don't want people to be able to take control of my version of Box2D. If I accept significant amounts of code into the my Box2D code base, then I don't feel like it is 100% mine.

**Comment by JesseTG** [comment]
> I think it would be ethically (and probably legally) wrong for me to sell a version of Box2D in the future if that version contained major pieces of code written by other people. I'm not saying that is my plan, but I don't want to rule it out.

Contributors must sign a CLA in which they grant you the right to do this with their additions.  Done.

> I'm totally fine with forking. I'm fine with giving other people control of their version of Box2D. I just don't want people to be able to take control of my version of Box2D. If I accept significant amounts of code into the my Box2D code base, then I don't feel like it is 100% mine.

Sure, and that's great, but then we have major fragmentation, and then different forks of Box2D will each add different neat things, some of which are incompatible with each other, others that break APIs, still others that require the planets to be aligned in a certain way, etc., and then someone has to go in and make a "best of" fork, which brings us back to square one.

**Comment by Alicemargatroid** [comment]
As an addendum, did you write C++? The tools that compile it? The standard library? All the other supporting structures that allow Box2D to exist and thrive? Of course not! That would be absurd!

The creation, the derived art, is yours; no matter even if someone forks it, it will always be yours. Arguing percentages and such is a waste of time.

However, as noted, under the zlib license, if you wish to later fork your own code and sell it under a more restrictive license, there are legal instruments to allow that; you wouldn't even need CLA's as Jesse helpfully pointed out, due to how zlib works.

**Comment by louis-langholtz** [comment]
Are there specific changes to the Box2D library that you would like to see (besides bug fixes and a change to the contribution policy)?

**Comment by PlanetVaster** [comment]
I have made a forked version of Box2D that allows contributions from the community, called OpenBox2D. You can check it out [here](https://github.com/PlanetVaster/OpenBox2D).

**Comment by louis-langholtz** [comment]
@PlanetVaster BTW, there are others already that are open to contributions. Not clear Erin's okay with using issue to advertise them though.
