### ISSUE TITLE
CMake build error on Windows

### ISSUE THREAD

**Issue by CesarNoll** [erincatto/Box2D#426]
I'm trying to build Box2D but I got this message while configuring:

You have called ADD_LIBRARY for library glfw without any source files. This typically indicates a problem with your CMakeLists.txt file

When I click to generate I get this error message:

CMake Error at Testbed/CMakeLists.txt:84 (add_executable):
Cannot find source file:

Framework/imgui.h
Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
 .hxx .in .txx

CMake Error: Cannot determine link language for target "glfw".
CMake Error: CMake can not determine linker language for target: glfw

Any ways to fix this?

**Comment by 1aam2am1** [comment]
Turn off the option to build example.

**Comment by CesarNoll** [comment]
Solved, thank you. But if I wanted to build the examples, how can I fix this?

**Comment by 1aam2am1** [comment]
You must install glfw.

**Comment by CesarNoll** [comment]
But I have glfw installed on my computer.

**Comment by 1aam2am1** [comment]
Then you must in cmake option set where is installed glfw in your computer.

**Comment by Spoon94** [comment]
http://blog.csdn.net/sinat_23185975/article/details/53323241

**Comment by Timmmm** [comment]
No I'm pretty sure this is a bug in the CMakeLists.txt. It clearly tries to add these files:

```
# Define the framework files.
set(Testbed_Framework_SRCS
	Framework/DebugDraw.cpp
	Framework/DebugDraw.h
	Framework/imgui.h
	Framework/imgui.cpp
	Framework/Main.cpp
	Framework/RenderGL3.cpp
	Framework/RenderGL3.h
	Framework/Test.cpp
	Framework/Test.h
)
```

When only these files exist in the repo:

	Framework/DebugDraw.cpp
	Framework/DebugDraw.h
	Framework/Main.cpp
	Framework/Test.cpp
	Framework/Test.h

I guess these tests haven't actually been run in a while!

You can remove those files from the `Testbed_Framework_SRCS` but it still fails in some `glfw/CMakeLists.txt` anyway. I think the CMake support hasn't been maintained.

**Comment by 1aam2am1** [comment]
Box2d is not maintained long time.

**Comment by Timmmm** [comment]
I didn't know that. There are still commits... Anyway is there a newer alternative?

**Comment by louis-langholtz** [comment]
By newer alternative do you mean that are you specifically looking for a fork that's has CMake support working for the Testbed for your platform, or are you looking for a newer alternative that has more general updates?

Just my two cents worth...

I ask because for the former, I think it's impressive that Erin's put together as much cross-platform support for the Testbed as he has. It's not as easy a thing to do IMO as supporting a cross-platform library especially since the Testbed depends on other projects like GLFW and GLEW. One certainly doesn't have to have the Testbed compiled and built in order to use the Box2D physics library. Erin could make the choice to just cut the Testbed out of the Box2D distribution and save himself the headache that it creates with keeping things like this up-to-date. I have no idea if he's considering that but I am for my fork.

As to the latter possibility, looking for more general updates, I've seen requests asking for new updates before but none that elaborated on what they'd like from the new updates. Erin seems like an incredibly smart guy who could potentially deliver a lot of other incredible things and I do myself wonder what sort of new things he might be considering. Perhaps the thing that impresses me the most about what he's done so far with the Box2D library however, is how few things I've been able to find that I'd consider bugs. It's a pretty solid library that way and I could see people arguing to leave good-enough alone. So if by updates one were looking for general bug fixes, then what would those be if not for building the Testbed?

Anyways, while I have opinions about this, I would sincerely like to hear more from other people about what their perspectives are on these things and what they'd like to see done for addressing them.

**Comment by erincatto** [comment]
You can now build the testbed using Premake5. Please see Building.txt.

**Comment by Timmmm** [comment]
@louis-langholtz: I just had a vague recollection of a newer library that supported deformable bodies. Must have been thinking of LiquidFun but that is just an extension of Box2d anyway so never mind!
