### ISSUE TITLE
Use Box2D with QT 5.8 (MinGW 32bit)

### ISSUE THREAD

**Issue by BlackStef** [erincatto/Box2D#442]
I have some isue trying to create a C++ librairy on QT based on Box2D. 
I juste want to integrate box2D with my QT project but impossible, I have somes errors with include header file (#include "Box2D/Collision/Shapes/b2ChainShape.h")

 erreur : Box2D/Collision/Shapes/b2ChainShape.h: No such file or directory; but I can see the file in the Shapes folder in my project view ! 

I just have trying to follow this tuto : https://www.youtube.com/watch?v=vg4BQoPuEUI&t=415s

Thank for your help :)

**Comment by 1vanK** [comment]
try #include <Box2D/Box2Dh>

**Comment by xyng** [comment]
This is most likely not a problem with this library but with your environment.
We recently used QT with Box2D in a project and did not run into those problems.

You probably have set the wrong includepath for your project.

But in general I'd advise you to use cmake instead of QT's qmake, since Box2D serves you with cmake plugins to find it's include paths.

You'll find plenty of online tutorials on how to integrate these three.

**Comment by erincatto** [comment]
xyng is correct. This is a problem with BlackStef's build configuration.
