### ISSUE TITLE
Linear Damping formula seems to be missing mass scaling.

### ISSUE THREAD

**Issue by FurryFur** [erincatto/Box2D#454]
I noticed that when using Box2D, linear damping felt off. I checked the code and noticed that the ODE being solved is dv/dt + c * v = 0. However, I believe this should be m * dv/dt + c * v = 0, otherwise changing the mass of an object has unexpected results. I expect that when I increase the mass of an object, it will speed up slower, and slow down slower. However, this isn't what happens, unless I divide the linear damping by mass, which then gives the result I expected.

Here is the relevant code starting on line 209 of b2Island.cpp:
```c
// Apply damping.
// ODE: dv/dt + c * v = 0
// Solution: v(t) = v0 * exp(-c * t)
// Time step: v(t + dt) = v0 * exp(-c * (t + dt)) = v0 * exp(-c * t) * exp(-c * dt) = v * exp(-c * dt)
// v2 = exp(-c * dt) * v1
// Pade approximation:
// v2 = v1 * 1 / (1 + c * dt)
v *= 1.0f / (1.0f + h * b->m_linearDamping);
w *= 1.0f / (1.0f + h * b->m_angularDamping);
````

**Comment by erincatto** [comment]
Think of b->m_linearDamping as c/m. This is an arbitrary choice with none better than the other except that the units for b->m_linearDamping are simpler. This makes it somewhat easier to tune.

**Comment by FurryFur** [comment]
I disagree with this, what if your mass is not constant, and is changed at runtime. Even in the case where the mass is constant, if I want to tweak my parameters, increasing mass should should make my object harder to stop. I'm sure most people believe that this variable is k in the equation F=-kv as well, I don't think people should have to look at the code to figure out that it's not.

**Comment by erincatto** [comment]
Your case makes perfect sense and is mathematically valid. Different users of Box2D have different needs and different points of view. In some cases it is not possible to please everyone.

Imagine this user: "I tried setting the damping parameter on various bodies so they all slow down at the same rate. However, I don't have a good sense for the units of the damping parameter, they are in units of kg * m / s. Can Box2D provide a function to tune the damping parameters for a set of bodies so they all slow down at the same rate, regardless of their mass?"

Or this user: "I have a body with that changes mass often and it has some linear damping. I need the body to slow down at the same rate regardless of the mass. Can you provide an option to change the damping automatically so that the damping strength remains the same regardless of the mass?"

That said, I agree that the units should be documented and I will do so.

**Comment by erincatto** [comment]
https://github.com/erincatto/Box2D/commit/a03a41934e87b5515dcefccde8a2b8ddd136b130
