### ISSUE TITLE
Bullet body with fixture isSensor does not use continuos collision detection

### ISSUE THREAD

**Issue by ratuple** [erincatto/Box2D#457]
The bullet flag has no effect if each fixture has isSensor set to true. The body can glitch through other bodies with this setup.
Body: bullet = true
Fixture: isSensor = true

As a bullet should often only do damage and not move the colliding body, i guess this is a pretty regular scenario.

**Comment by erincatto** [comment]
For bullets you should use a ray cast not a sensor. Sensors are only meant to detect persistent overlap.

**Comment by ratuple** [comment]
@erincatto thanks for the quick answer.
My "bullet" is a shot which should be impacted by gravity and takes some time to fly.
The reason i used isSensor is to not impact the collided body (e.g. changing targets velocity by the impact).
Because the combination of isBullet and isSensor does not work i am now disabling contacts for shots/bullets with the contactListener in preSolve which leads to similar results.
I consider this a workaround but can see that there are indeed only a few use-cases from a physics perspective. But i think exactly the use-case of a non-impacting shot is necessary quite often and would be solved more beautifully with isSensor.

Anyhow, thanks for great library and the quick support!

**Comment by erincatto** [comment]
It is tempting to use a rigid body for projectiles in order to get the affect of gravity. However, typically you do not need the projectile to interact with other rigid bodies in the solver. Sensors seem like an option, but they were not developed for this purpose.

I recommend to generate a series of ray casts and to model gravity on your own. This gives the best result in my experience.
