### ISSUE TITLE
**Vertex** Methods have disapeared from b2PolygonShape

### ISSUE THREAD

**Issue by abakobo** [erincatto/box2d#462]
b2PolygonShape::GetVertexCount() and b2PolygonShape::GetVertex(int32) have been removed at a time.

This have caused me some backward compatibility problem. But the methods don't look like they could have conflict with anything new..?

You can create a pull request with this compare link if you want to put them back:
https://github.com/erincatto/Box2D/compare/master...abakobo:b2Polyshape-VertexMethods

**Comment by louis-langholtz** [comment]
This is Interesting and a surprise to me. It appears these methods were removed in commit dca0c259827f04d097cac123b39a4f5103be855f which is dated May 21, 2017.

I wonder what the thinking was behind removing these methods. Did Erin intend for this change? The commit message states "C++11 stuff: override and nullptr`. Nothing about this message relates to taking away those methods; at least not to me.

I suppose an argument could be made that these methods decreased encapsulation given that `m_vertices` was publicly accessible (since Feb 26, 2012 at least). I'm more of the opinion though that `m_vertices` (and the other member variables) shouldn't be public to begin with; in which case having the `GetVertexCount` and `GetVertex` methods I think makes more sense. The latter is my preference since the class code has the opportunity to provide a contract - of a polygon shape which requires a winding order (CCW I believe), convexity, and related edge normals - and the opportunity to enforce it (via the member variables being private and only allowing access through methods).

**Comment by erincatto** [comment]
I have these members public to improve debug performance.
