### ISSUE TITLE
Where is the build folder?

### ISSUE THREAD

**Issue by giveflow** [erincatto/Box2D#471]
Usually there is a build folder where I can easily build up for either my xcode or visual stdio.

Where is it now?

**Comment by louis-langholtz** [comment]
FYI I don't know for sure but in the interests of trying to be a helpful member of the community...

I believe that folder went away. It's use having been replaced more fully with the use of  premake. At least in the latest code on GitHub.

If you didn't want to use premake , you can go back a bit in the git history and build from an earlier commit that still has the build folder with project files in it. Not sure which commit you'd need to go back to though.

**Comment by giveflow** [comment]
I am new in Box2D engine. So I dont really know how to setup premake in Xcode. The instruction file has just  a few lines to mention the setup in both xcode and visual studio.

If you can give me a detailed setup information, I am so ready for premake.

**Comment by louis-langholtz** [comment]
I'm a total noob to premake. But reading the [Using Premake](https://github.com/premake/premake-core/wiki/Using-Premake) online web page shows the command line usage of `premake5 xcode4` is the action to generate an xcode file that'd presumably get you back to being able to use xcode.

Otherwise, as far as going back in the git history, I imagine you could do the git clone of the repo and then checkout the `v2.3.1` git tab commit state to have yourself the build folder again. At least that's the latest git tag I found doing a `git tag` listing in my clone of Erin's Box2D code. 2.3.2 was the newest release that I saw the folder in but I don't know what commit that was released at and I don't see a tag for it either.

**Comment by giveflow** [comment]
Thanks, I will give it a try.

**Comment by drewish** [comment]
For reference if you've got homebrew installed you can get premake setup by running:
```
brew install --devel premake
```

**Comment by erincatto** [comment]
Yeah, use this:
premake5 xcode4
