### ISSUE TITLE
Motor joint appears to have non-physical behavior

### ISSUE THREAD

**Issue by elemel** [erincatto/Box2D#487]
A system formed by two dynamic bodies connected by a motor joint doesn't look realistic when e.g. falling to the ground.

Screenshot:

<img width="1136" alt="screen shot 2018-03-11 at 11 01 23" src="https://user-images.githubusercontent.com/31885/37252118-0d9aa9a6-251c-11e8-8936-f28cd4a77746.png">

(After falling to the ground, the bodies come to rest and fall asleep in an unbalanced position.)

Testbed repro:

https://github.com/elemel/Box2D/commit/01bae74c52b9e089b04dda8899d8aba9d901ef22

My best guess is that the linear friction code doesn't calculate the resulting torque in the way I expect. Shouldn't the friction force be applied at the world-space linear offset for both bodies?

**Comment by erincatto** [comment]
Thank you for bug report and test case. There was a subtle math problem in the joint constraints.
https://github.com/erincatto/Box2D/commit/33af62e357051801afc6143107fc1be9e41ae9aa

**Comment by NicoKiaru** [comment]
Hmm I implemented this bug fix in the java port jbox2d library, according to the mentioned commit (only one commit, right?). But I get some very strange behaviour with this fix. I'll try to document it better, but in brief: in zero gravity, when I have 2 motor joints linked to the same object, and when I move forth and back one of this object (using the setLinearOffset method), the total angular momentum of the three objects is clearly not conserved (-> starts rotating out of the blue).

If you think that's something worth investigating, I can try to give you a simple example code.

**Comment by NicoKiaru** [comment]
Ok, I could open a new issue, but I think the problem occurs with this fix (which is definitely improving the behaviour, don't get me wrong), so I'll post here. First, I'm sorry I tried to make the c++ version testbed version work, but I couldn't because my computer do not support the OpenGL version used. However, I think the problem is easy to test. In the ``` MotorJoint.h``` test, just replace the following piece of code:
https://github.com/erincatto/Box2D/blob/8cbddc3328ea648c998427fccee7715ab409548c/Box2D/Testbed/Tests/MotorJoint.h#L44-L65
By something along these lines (I translated my java code, there could be some typo):
```
    m_world->setGravity(b2Vec2(0.0f, 0.0f); // Zero gravity
    // Define motorized bodies
    {
        b2BodyDef bd;
        bd.type = b2_dynamicBody;
      
        // Creates first body
        bd.position.Set(0.0f, 8.0f);
        b2Body* body1 = m_world->CreateBody(&bd);
      
        b2CircleShape circle1;
        circle1.SetRadius(2.0f);
      
        b2FixtureDef fd;
        fd.shape = &circle1;
        fd.friction = 0.0f; // No friction
        fd.density = 2.0f;
        body1->CreateFixture(&fd);

        // Creates second body
        bd.type = b2_dynamicBody;
        bd.position.Set(6.0f, 8.0f);
        b2Body* body2 = m_world->CreateBody(&bd);
      
        b2CircleShape circle2;
        circle1.SetRadius(1.0f);

        fd.shape = circle2;
        fd.friction = 0.0f; // no friction
        fd.density = 2.0f;
        body2->createFixture(&fd);      
      
        b2MotorJointDef mjd;
	mjd.Initialize(body1, body2);
	mjd.maxForce = 1000.0f;
	mjd.maxTorque = 0.0f; // no need for torque
        m_joint = (b2MotorJoint*)m_world->CreateJoint(&mjd);
    }
```
Then in the step method, use this one:
```
                if (m_go && settings->hz > 0.0f)
		{
			m_time += 1.0f / settings->hz;
		}

		b2Vec2 linearOffset;
                // simple circular movement
		linearOffset.x = 6.0f * cosf(5.0f * m_time);
		linearOffset.y = 6.0f * sinf(1.0f * m_time);
		
		float32 angularOffset = 4.0f * m_time;

		m_joint->SetLinearOffset(linearOffset); 
		// Disable angular offset
                //m_joint->SetAngularOffset(angularOffset);

		g_debugDraw.DrawPoint(linearOffset, 4.0f, b2Color(0.9f, 0.9f, 0.9f));

		Test::Step(settings);
		g_debugDraw.DrawString(5, m_textLine, "Keys: (s) pause");
                m_textLine += 15;
```

In such a test, if you activate the motor, everything looks fine. But when you inactive it by retyping s, the systems keeps rotating, which means that its total angular momentum has increased. But no external torque was applied. I made a quick video here of this behaviour here: https://youtu.be/aVEIr5oBJKk.

Another joint may do the trick here, but I need a motor joint in my application.

Hope that's helpful!

Nicolas
