### ISSUE TITLE
Step() function get stuck

### ISSUE THREAD

**Issue by xiajiaonly** [erincatto/box2d#532]
![image](https://user-images.githubusercontent.com/4102643/52530133-83426e00-2d3b-11e9-8e7d-a972e8ec09da.png)

when a dynamic body is covered by many static bodies.
for example:
use mouse to draw many lines，a line is a static body.
then the dynamic body will be blocked by the lines.
when the lines cover the dynamic body,the Step() will get stuck.
maybe 10 lines or more or less.

How to solve this problem?
![image](https://user-images.githubusercontent.com/4102643/52531475-ee4a6f80-2d50-11e9-8ad9-1609b21c7a31.png)

**The FPS is very very low.**

**Comment by HughPH** [comment]
What behaviour do you want in this scenario?

**Comment by xiajiaonly** [comment]
I think the dynamic body  should be stuck and in a static state.

**Comment by HughPH** [comment]
I'm not sure I understand. If it's static, it won't move. If it's blocked,
it won't move.

**Comment by xiajiaonly** [comment]
It jumps in box2D.
In reality, it should be an illegal state.
Whatever the state it is, it should not increase the consumption of world's Step ().

**Comment by HughPH** [comment]
Ok, so it's not "stuck".

If a dynamic object is over another object, it will push away from the
centre of the other object. Most physics engines will do the same. If you
want your object to be static, make it static. Otherwise it will have
dynamic behaviours. If you want to pretend the object is on another plane,
so they shouldn't interact, you should use the category bits and mask bits.

There are great tutorials at www.iforce2d.net/b2dtut/

**Comment by xiajiaonly** [comment]
T.T，You misunderstood me.I don't care about the state of the object. What I care about is that the Step() function will be stuck.Maybe this needs a GIF to explain it more accurately.

**Comment by HughPH** [comment]
Ok, so you call Step and it locks up?

How many iterations are you asking it to perform?

**Comment by xiajiaonly** [comment]
m_pWorld->Step(1.0f / 60.0f, 4, 2);

**Comment by HughPH** [comment]
It would seem strange for this not to have been discovered before. You
could use iforce2d's RUBE to model the same scene (export a breaking
example or create the objects in RUBE, save it, and change the file in
notepad to have the same object properties) and see if that suffers the
same issue. If it does, you have something reproducible. Otherwise, it's
likely something peculiar to your code.

     - Hugh

--------------------------
"Bureaucracy is the epoxy that greases the wheels of progress."
  - James H. Boren

**Comment by xiajiaonly** [comment]
the code modify from the testbed,is here:https://github.com/xiajiaonly/TestB2D
![image](https://user-images.githubusercontent.com/4102643/52540600-525b4b00-2dc6-11e9-91e2-1c5c58959f9b.png)
Because of the limited time, I haven't written a typical example. I will revise this example in the next step to make the problem more typical.

**Comment by erincatto** [comment]
I looks like the complexity of your static model is the problem. Simplify, then simplify again.

**Comment by HughPH** [comment]
Yeah, I was going to say that looks pretty crazy. How many objects do you
have there?

**Comment by xiajiaonly** [comment]
It doesn't need a lot. In some cases, just a few. In the above examples, some are unnecessary, just to illustrate the problem. I will revise the example above. Yes, the problem is more prominent. I just got up. Wait a minute.

**Comment by xiajiaonly** [comment]
I have updated the code.
![image](https://user-images.githubusercontent.com/4102643/52545456-9ebc8000-2df2-11e9-8ae5-0ea7db23cdf8.png)
“body sum” just the  lines sum，in up pic.
![image](https://user-images.githubusercontent.com/4102643/52545478-ce6b8800-2df2-11e9-8380-00f06dc932b3.png)
“body sum” include lines sum and balls sum,in up pic.

**Comment by HughPH** [comment]
Are you trying to make a solid body? You should use Polygons, not Lines...

**Comment by xiajiaonly** [comment]
Yes, it's the same.

**Comment by erincatto** [comment]
I experimented with this test case. The performance problem is definitely SolveTOI. The over-constrained bodies are trying to prevent tunneling. The solver fights harder for circles than polygons.
