### ISSUE TITLE
b2TimeOfImpact results in small overlaps

### ISSUE THREAD

**Issue by MelvMay-Unity** [erincatto/box2d#552]
b2TimeOfImpact leads to small overlaps no matter what shapes are used.  Attached is a testbed example showing this in the most simple case of two circles.

[TimeOfImpactBug.h.txt](https://github.com/erincatto/Box2D/files/3446936/TimeOfImpactBug.h.txt)
![testbedoverlap](https://user-images.githubusercontent.com/5794808/62132965-ee760180-b2d5-11e9-8eaa-31d1a4df45bf.png)

**Comment by louis-langholtz** [comment]
I believe that this overlap is part of the design per settings like `b2_linearSlop` and `b2_polygonRadius` effecting `target` in [`void b2TimeOfImpact(b2TOIOutput* output, const b2TOIInput* input)`](https://github.com/erincatto/Box2D/blob/master/Box2D/Collision/b2TimeOfImpact.cpp#L254).

**Comment by MelvMay-Unity** [comment]
The overlap is fixed independant of b2_polygonRadius or the actual radius of the circles.  It's directly related to b2_linearSlop though. To me it's unexpected because I would expect the time-of-impact to not cause overlap but to be near the impact point or in the case of polygons within the polygon radius.

Of course this doesn't mean my expectation is correct.

**Comment by erincatto** [comment]
Yeah, this is by design.
```
	float totalRadius = proxyA->m_radius + proxyB->m_radius;
	float target = b2Max(b2_linearSlop, totalRadius - 3.0f * b2_linearSlop);
```
Your test case is hitting this target very closely since it is just translation. Thanks for providing the test code.

Why do I want overlap? In general Box2D uses overlap to help ensure contact points are persisted from frame to frame. This improves stability by warm starting the solver with the previous frame's contact forces.
