### ISSUE TITLE
Gravity way to strong

### ISSUE THREAD

**Issue by HabButterimAuge** [erincatto/box2d#558]
Hello!

I created my own first programm with Box2d (not a test of the tesbed) but my gravitation is way too strong. The body falls extremely fast although I use the same values as the testbed.
Heres my code:
https://pastebin.com/gr9pNzSS

**Comment by waterimp** [comment]
@HabButterimAuge - I am pretty sure this is a framerate issue in your code and not a gravity issue.

Let me summarize the flow I am seeing in your code:

```c++
float32 timeStep = 1.0f / 60.0f;
...
while (m_MainWindow.isOpen())
{
     ...
     m_World->Step(timeStep, velocityIterations, positionIterations);
     ...
}
```

I am not familiar with the framework you are using, but I am not seeing anything that is limiting your framerate. For each iteration of your while loop `while (m_MainWindow.isOpen())`, is it guaranteed to march along at 60 FPS, or is it going to run as fast as your computer will let it? I will assume it is running as fast as it can and provide some more thoughts.

Consider implementing all of these points:
1. check the elapsed time each iteration of the `while (m_MainWindow.isOpen())` loop.
2. do one of these:
   * accumulate elapsed time and run `m_World->Step()` with your 1/60 timstep only when that much time has been accumulated.
   * pass in the elapsed time into  `m_World->Step()` instead of a constant 1/60 timestep.
3. consider sleeping / controlling the framerate when the loop is running too fast.

I hope this information is helpful in getting your project's speed under control. I am pretty confident it is the time that is running too fast and not the gravity that is too strong.

**Comment by erincatto** [comment]
Thanks @waterimp for answering this.
