### ISSUE TITLE
Body not slowing down with friction for static body (Bug)

### ISSUE THREAD

**Issue by luisgrimaldo** [erincatto/box2d#604]
It seems like there's a bug in the following set-up, reproducible by with the default settings and Step(1/60f, 8, 8) (not the test-bed settings):
```
b2Vec2 gravity;
gravity.Set(0.0f, -10.0f);
m_world = new b2World(gravity);
b2ChainShape chainShape;
b2Vec2 vertices[] = {b2Vec2(-5,0), b2Vec2(5,0), b2Vec2(5,5), b2Vec2(4,1), b2Vec2(-4,1), b2Vec2(-5,5)};
chainShape.CreateLoop(vertices, 6);

b2FixtureDef groundFixtureDef;
groundFixtureDef.density = 0;
groundFixtureDef.shape = &chainShape;

b2BodyDef groundBodyDef;
groundBodyDef.type = b2_staticBody;

b2Body *groundBody = m_world->CreateBody(&groundBodyDef);
b2Fixture *groundBodyFixture = groundBody->CreateFixture(&groundFixtureDef);

b2CircleShape ballShape;
ballShape.m_radius = 1;

b2FixtureDef ballFixtureDef;
ballFixtureDef.restitution = 0.75f;
ballFixtureDef.density = 1;
ballFixtureDef.shape = &ballShape;

b2BodyDef ballBodyDef;
ballBodyDef.type = b2BodyType::b2_dynamicBody;
ballBodyDef.position = b2Vec2(0, 10);

b2Body *ball = m_world->CreateBody(&ballBodyDef);
b2Fixture *ballFixture = ball->CreateFixture(&ballFixtureDef);
ball->ApplyForceToCenter(b2Vec2(-1000, -400), true);
```
As you'll see the ball at the end is meant to stop and in fact, if you choose the ground to be dynamic body instead of static, the ball will stop, but when it's dynamic and the ball is supposed to stop it will pick up speed. Doesn't seem related to the recent changes with density zero improvement. I was able to repro it even in previous commits to that.

**Comment by HughPH** [comment]
I couldn't reproduce it in C# so I copied it into the testbed (and changed the Position iterations to 8) and I still can't reproduce it:
![Peek 2020-06-26 15-58](https://user-images.githubusercontent.com/26636183/85871304-1b70b400-b7c6-11ea-8923-b849e0a5adf2.gif)

Sure the ball bounces off a little at the end and rolls away very slowly, but I don't see it picking up speed.

**Comment by luisgrimaldo** [comment]
That's reproducing right there, but you are cutting the video right when it's about to pick up speed, the pick up in speed is very minimal, right when you cut it the ball will keep on rolling at that very slow speed until it reaches the other side, and it'll be about 0.0001 mps faster at the end. The body never actually sleeps.

**Comment by HughPH** [comment]
Does it continue to pick up speed, or does it just pick up speed at that moment and then maintain a constant velocity? I ask because I can't see any increase in speed over time.

I see the same with 3 Position Iterations as I do with 8.

This might be explained by the fact that you have a circle with some inertia against a surface with some friction. You can, for example, drop a high friction polygon onto a circle placed on a low friction surface, such that the circle will spin against the low friction surface and spin contrary to its direction of travel. If there's not enough rotational force, the friction will take over and while the circle will stop rotating for a moment, it will immediately start rotating in the direction of travel.
![Peek 2020-06-26 19-27](https://user-images.githubusercontent.com/26636183/85889273-0f471f80-b7e3-11ea-91c2-a18db46e0979.gif)

**Comment by HughPH** [comment]
Looks to me like it just bounces off that left hand edge. You can see the long spike when it makes contact - that's the Contact Impulse.
![Peek 2020-06-26 19-36](https://user-images.githubusercontent.com/26636183/85890010-71545480-b7e4-11ea-92d1-6a4b704fada9.gif)

**Comment by luisgrimaldo** [comment]
yes, it does bounce off but it is just after that bounce of that the object never stops, and if after that bounce you log the velocity until the object reaches the other side, you'll notice the velocity gain

**Comment by HughPH** [comment]
So it bounces and you want it not to bounce? Bear in mind your "wall" is also at an angle, and the ball is not touching the "floor" when it hits the "wall", so you have gravity contributing too.

**Comment by luisgrimaldo** [comment]
No, I don't want it not to bounce, the bouncing is fine, what I think it should do like any other rigid body is to eventually slow it's velocity due to the friction but that's not happening correctly. as the speed is increasing (very slightly but still increasing). Isn't this a non-physical effect?

**Comment by HughPH** [comment]
Well you have no friction on any of your objects, and in any case I don't think that would help here since friction applies to two surfaces moving against each other (see my GIF with the circle changing direction). What you really want is Rolling Resistance, but that's not a feature of Box2D (as it stands). Try setting an Angular Damping value on the body, that should give you the effect you're looking for.

**Comment by luisgrimaldo** [comment]
There is friction, they are the default 0.2f friction which should be enough to stop the ball from rolling. Changing angular damping will probably stop this but it's not realistic to change that property.

**Comment by HughPH** [comment]
OK, you're right about the default Friction

`	b2FixtureDef()
	{
		shape = nullptr;
		userData = nullptr;
		friction = 0.2f;
		restitution = 0.0f;
		density = 0.0f;
		isSensor = false;
	}`

However, Friction won't slow down a circle rotating in the "right" direction because there is no friction between two solid surfaces. This is like rolling a glass bead on a marble floor - except that we're also not measuring losses from air resistance or energy turned into sound, so the loss as far as Box2D is concerned is zero. The friction you get with a car wheel on tarmac, for example, is in the flexing of the tyre. The friction between the rubber and the road is still small - you can pick tyre rubber with your finger nails, but we still get tens of thousands of miles out of that rubber even in contact with rough road surfaces.

**Comment by luisgrimaldo** [comment]
I understand that, why is the behavior different when you switch the `ground` body type to be dynamic instead of static? in that case, the ball actually stops rolling.
Also, your point makes sense but it still doesn't explain why the ball's velocity would increase, if there was no energy loss at all from friction or air resistance or any other external factors, at best the velocity would remain the same but not increase.

**Comment by HughPH** [comment]
I thought we'd established that the increase in speed was from the ball bouncing off the wall, and/or that it only increases at that point? My theory about the ball having some 'backwards' rotation I think still holds water there.

I don't know why you get different behaviour with a dynamic body, since `b2CollidePolygonAndCircle` doesn't check body types. However, I would expect that the bodies are interacting differently and therefore having a different effect on each other: static body position & velocity constraints are skipped, because that's what static means. A dynamic body will have those calculated, which means there are body forces at play. Even if your "ground shape" is still (not static), it will continue to push away from the ball as the ball collides with it.

The tiny, tiny values don't mean a lot, and Box2D is neither guaranteed nor even intended to produce perfect results. Different IEEE FP implementations will give results different enough that Box2D can't be guaranteed to give the same answers between two architectures. Even in C# compiling a debug build and running with the debugger produce two different outcomes, which are each different to the optimised code. Erin put a link to an article called, I think, "How to break the IEEE Floating Point standard" which basically takes a lot longer to say the above.

**Comment by luisgrimaldo** [comment]
Actually upon further inspection, the speed is actually slowing down just very slowly.
And yes, there is some negative angular velocity still in the object.
Another thing I noticed is that the angular velocity happens to be almost the exact same (except in the opposite direction) and maybe that's causing this artifact, but friction should take care of it as a coefficient of 0.2 friction should be enough to break the movement at this speed, am I wrong? (Please watch the whole video attached)
[test.mov.zip](https://github.com/erincatto/box2d/files/4839685/test.mov.zip)

**Comment by HughPH** [comment]
Negative angular velocity is clockwise. I was more interested in the angular velocity just before it hits the wall.

**Comment by Zonciu** [comment]
When ground body is dynamic:
![image](https://user-images.githubusercontent.com/10374056/86429378-ef9f8200-bd21-11ea-9328-8a95dd5fb794.png)
```
		b2Vec2 gravity;
		gravity.Set(0.0f, -10.0f);
		m_world->SetGravity(gravity);
		b2ChainShape chainShape;
		b2Vec2 vertices[] = { b2Vec2(-5,0), b2Vec2(5,0), b2Vec2(5,5), b2Vec2(4,1), b2Vec2(-4,1), b2Vec2(-5,5) };
		chainShape.CreateLoop(vertices, 6);

		b2FixtureDef groundFixtureDef;
		groundFixtureDef.density = 0;
		groundFixtureDef.shape = &chainShape;

		b2BodyDef groundBodyDef;
		groundBodyDef.type = b2_dynamicBody;  // difference

		b2Body* groundBody = m_world->CreateBody(&groundBodyDef);
		b2Fixture* groundBodyFixture = groundBody->CreateFixture(&groundFixtureDef);

		b2CircleShape ballShape;
		ballShape.m_radius = 1;

		b2FixtureDef ballFixtureDef;
		ballFixtureDef.restitution = 0.75f;
		ballFixtureDef.density = 1;
		ballFixtureDef.shape = &ballShape;

		b2BodyDef ballBodyDef;
		ballBodyDef.type = b2BodyType::b2_dynamicBody;
		ballBodyDef.position = b2Vec2(0, 10);

		b2Body* ball = m_world->CreateBody(&ballBodyDef);
		b2Fixture* ballFixture = ball->CreateFixture(&ballFixtureDef);


		ball->ApplyForceToCenter(b2Vec2(-1000, -400), true);
```

**Comment by erincatto** [comment]
Please look at #617 
The ball is rolling without sliding and keeping constant kinetic energy to a high precision. Surface friction in Box2D does not provide rolling resistance. This could be added as an enhancement.

Please re-open if I missed anything.
