### ISSUE TITLE
b2World listeners getter methods

### ISSUE THREAD

**Issue by niedzadr** [erincatto/box2d#608]
Would be convenient to have following methods on b2World:

- b2DestructionListener* GetDestructionListener()
- b2ContactFilter* GetContactFilter()
- b2ContactListener* GetContactListener()
- b2Draw* GetDebugDraw()

I use some helper functions that take b2Body* as argument and need to access some of the above objects. I'd like to avoid passing them to the function myself since the world object can be accessed through the body.

**Comment by Hexlord** [comment]
Personally I do not think accessing world through body in you business logic is a good architectural decision. The fact that it is there is a matter of performance or old design, I would guess.

**Comment by niedzadr** [comment]
@Hexlord You're probably right, but still having those getters would be handy.

**Comment by erincatto** [comment]
This has come up before. People often want to use Box2D as data storage for game data. I support void* on bodies, fixtures, and joints. This makes sense when you can query a world using a raycast and need to get back to game data or there is some implicit destruction event. However, there is no situation where you receive a world pointer that is not already in scope in user code. If there is please let me know.

Otherwise I recommend implementing this data structure in your code in some form or another:

```cpp
struct MyWorld
{
  b2World* world;
  b2DestructionListener* destructionListener;
  // etc.
};
```

This way you can always get at your data.

**Comment by erincatto** [comment]
Closing due to lack of further discussion.
