### ISSUE TITLE
Zero initialization of b2Vec2

### ISSUE THREAD

**Issue by mwthinker** [erincatto/box2d#683]
```cpp
// Default initialization
b2Vec2 pos;
```
```cpp
// Zero initialization
b2Vec2 pos{};
```
but I think the expected behavior is Zero initialization for the second version.
```cpp
struct B2_API b2Vec2
{
      b2Vec2() = default;
// ...
};
```
By doing this you get no performance hit by default but still give the user a possibility to zero initialization. And no surprise when it is not zero initialized,

**Comment by franklange** [comment]
I checked the initialization jungle on cppreference.com and since all the math classes:
a) are all trivially constructable and
b) don't have user-defined default constructors

this should work.
Opened a PR on my fork since it said PRs are generally discourage here on the main repo?
https://github.com/franklange/box2d/pull/1

Let me know if this is wanted and I'll point it to master here :)

**Comment by erincatto** [comment]
Thanks for the report. I changed the default constructors in a1225ee95b1203b463b6d30469606a7a70899f67
